### ISSUE TITLE
Error updating to 1.0

### ISSUE THREAD

**Issue by wbyoung** [FWeinb/metalsmith-watch#20]
I just updated to version 1.0 and am getting this error:

```
/Users/wbyoung/Code/azul/node_modules/metalsmith-watch/dist/index.js:353
      originalOptions.close = function () {
                            ^
TypeError: Cannot set property 'close' of undefined
    at Gaze.watcherReady (/Users/wbyoung/Code/azul/node_modules/metalsmith-watch/dist/index.js:353:29)
    at null._onTimeout (/Users/wbyoung/Code/azul/node_modules/metalsmith-watch/node_modules/gaze/lib/gaze.js:427:24)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

**Comment by MoOx** [comment]
Oh. Can you just try pass an empty object as first parameters to this plugin ?

**Comment by wbyoung** [comment]
Thanks, the empty object fixed it. It probably still makes sense to address this. I opened a pull request, and will close this in favor of the pull request.
