### ISSUE TITLE
return path.charAt(0) === '/'; Error

### ISSUE THREAD

**Issue by jdsimcoe** [FWeinb/metalsmith-watch#23]
Here is the entirety of my `index.js` file:

```js
var
  Metalsmith  = require('metalsmith'),
  serve       = require('metalsmith-serve'),
  watch       = require('metalsmith-watch'),
  markdown    = require('metalsmith-markdown'),
  templates   = require('metalsmith-templates'),
  collections = require('metalsmith-collections'),
  permalinks  = require('metalsmith-permalinks'),
  coffee      = require('metalsmith-coffee'),
  sass        = require('metalsmith-sass'),
  Handlebars  = require('handlebars'),
  fs          = require('fs');


Handlebars.registerPartial('header', fs.readFileSync(__dirname + '/templates/partials/header.hbt').toString());
Handlebars.registerPartial('footer', fs.readFileSync(__dirname + '/templates/partials/footer.hbt').toString());

var findTemplate = function(config) {
  var pattern = new RegExp(config.pattern);

  return function(files, metalsmith, done) {
    for (var file in files) {
      if (pattern.test(file)) {
        var _f = files[file];
        if (!_f.template) {
          _f.template = config.templateName;
        }
      }
    }
    done();
  };
};

Metalsmith(__dirname)
  .use(serve({
    port: 8081,
    verbose: true
  }))
  .use(watch({
    paths: {
      "${source}/**/*": true,
      "templates/**/*": "**/*.md",
    },
    livereload: true,
  }))
  .use(collections({
    pages: {
      pattern: 'content/pages/*.md'
    },
    posts: {
      pattern: 'content/posts/*.md',
      sortBy: 'date',
      reverse: true
    }
  }))
  .use(findTemplate({
    pattern: 'posts',
    templateName: 'post.hbt'
  }))
  .use(markdown())
  .use(permalinks({
    pattern: ':collection/:title'
  }))
  .use(templates('handlebars'))
  .use(sass({
    outputStyle: 'compressed'
  }))
  .use(coffee())
  .destination('./build')
  .build(function(err, files) {
    if (err) { throw err; }
  });
```

When I run `node index.js` it returns the following error. Here is the entire strack trace:

```
[metalsmith-watch] ✓ Live reload server started on port: 35729
[metalsmith-serve] serving /Users/jdsimcoe/Sites/meetcircle/build at http://localhost:8081
path.js:479
  return path.charAt(0) === '/';
             ^
TypeError: Cannot read property 'charAt' of undefined
  at Object.posix.isAbsolute (path.js:479:14)
  at Object.posix.normalize (path.js:461:26)
  at /Users/jdsimcoe/Sites/meetcircle/node_modules/metalsmith-watch/dist/index.js:255:61
  at Array.map (native)
  at metalsmithWatch (/Users/jdsimcoe/Sites/meetcircle/node_modules/metalsmith-watch/dist/index.js:254:32)
  at next (/Users/jdsimcoe/Sites/meetcircle/node_modules/metalsmith/node_modules/ware/lib/index.js:68:8)
  at /Users/jdsimcoe/Sites/meetcircle/node_modules/metalsmith-serve/lib/index.js:52:5
  at [object Object].next [as _onTimeout] (/Users/jdsimcoe/Sites/meetcircle/node_modules/metalsmith/node_modules/ware/lib/index.js:68:8)
  at Timer.listOnTimeout (timers.js:110:15)
```

**Comment by MoOx** [comment]
Can you add (before all use()) `.source("./src")` and tell me if you still have the issue ?

**Comment by jdsimcoe** [comment]
Did this:

```js
Metalsmith(__dirname)
  .source('./src')
  .use(serve({
    port: 8081,
    verbose: true
  }))
  .use(watch({
    paths: {
      '${source}/**/*': true,
      'templates/**/*': '**/*.md',
    },
    livereload: true,
  }))
```
And it still fails with the same error.

**Comment by stevesunderland** [comment]
@jdsimcoe whats the solution for this? getting the same error: 

`return path.charAt(0) === '/';
             ^
TypeError: Cannot read property 'charAt' of undefined`

**Comment by jdsimcoe** [comment]
@stevesunderland Don't have a solution :crying_cat_face: wish I did.
