### ISSUE TITLE
Keeps trying to launch livereload server

### ISSUE THREAD

**Issue by mikestopcontinues** [FWeinb/metalsmith-watch#35]
Hey, I'm getting this error every time a file changes with `metalsmith-watch`. Using node 6.6.0, most recent version of metalsmith and metalsmith-watch.

Might be related to #26.

```
$ npm start

> bum@0.0.1 start /Users/msc/Sites/msct
> node --harmony index.js

[metalsmith-watch] ✓ Live reload server started on port: 3001
[metalsmith-express] ✔︎ Express listening at http://0.0.0.0:3000
[metalsmith-watch] ✔︎ Watching content/**/*
Build succeeded!
[metalsmith-watch] ✔︎ content/page/about.md changed
[metalsmith-watch] - Updating 1 file...

... Uhoh. Got error listen EADDRINUSE :::3001 ...
Error: listen EADDRINUSE :::3001
  at Object.exports._errnoException (util.js:1036:11)
  at exports._exceptionWithHostPort (util.js:1059:20)
  at Server._listen2 (net.js:1252:14)
  at listen (net.js:1288:10)
  at Server.listen (net.js:1384:5)
  at Server.listen (/Users/msc/Sites/msct/node_modules/metalsmith-watch/node_modules/tiny-lr/lib/server.js:162:15)
  at livereloadServer (/Users/msc/Sites/msct/node_modules/metalsmith-watch/dist/livereload.js:37:10)
  at exports.default (/Users/msc/Sites/msct/node_modules/metalsmith-watch/dist/index.js:239:46)
  at Ware.<anonymous> (/Users/msc/Sites/msct/ware/watchServer.js:57:7)
  at Ware.<anonymous> (/Users/msc/Sites/msct/node_modules/wrap-fn/index.js:45:19)
  at next (/Users/msc/Sites/msct/node_modules/ware/lib/index.js:85:20)
  at /Users/msc/Sites/msct/node_modules/wrap-fn/index.js:121:18
  at Ware.<anonymous> (/Users/msc/Sites/msct/node_modules/wrap-fn/index.js:45:19)
  at next (/Users/msc/Sites/msct/node_modules/ware/lib/index.js:85:20)
  at Ware.run (/Users/msc/Sites/msct/node_modules/ware/lib/index.js:88:3)
  at Metalsmith.<anonymous> (/Users/msc/Sites/msct/node_modules/thunkify/index.js:43:12)
  at next (/Users/msc/Sites/msct/node_modules/co/index.js:90:21)
  at Metalsmith.<anonymous> (/Users/msc/Sites/msct/node_modules/co/index.js:45:5)
  at Metalsmith.run (/Users/msc/Sites/msct/node_modules/unyield/index.js:29:17)
  at runAndUpdate (/Users/msc/Sites/msct/node_modules/metalsmith-watch/dist/index.js:146:14)
  at /Users/msc/Sites/msct/node_modules/metalsmith-watch/dist/index.js:198:5
  at done (/Users/msc/Sites/msct/node_modules/metalsmith-watch/node_modules/async/lib/async.js:132:19)
  at /Users/msc/Sites/msct/node_modules/metalsmith-watch/node_modules/async/lib/async.js:32:16
  at Metalsmith.<anonymous> (/Users/msc/Sites/msct/node_modules/metalsmith-watch/dist/index.js:188:7)
  at Immediate.<anonymous> (/Users/msc/Sites/msct/node_modules/co/index.js:52:14)
  at tryOnImmediate (timers.js:554:5)
  at processImmediate [as _immediateCallback] (timers.js:533:5)


You already have a server listening on 3001
You should stop it and try again.

[metalsmith-watch] ✔︎ Watching content/**/*
[metalsmith-watch] ✔︎ 1 file reloaded
```

**Comment by mikestopcontinues** [comment]
Perhaps also #31.

**Comment by mikestopcontinues** [comment]
Correction: #31 does not fix the issue.
