### ISSUE TITLE
TypeError: Cannot read property 'filename' of undefined

### ISSUE THREAD

**Issue by jcrawford** [FWeinb/metalsmith-watch#48]
```
[metalsmith-watch] - Updating 16 files...
/Users/Shared/Dropbox/Projects/jcrawford.github.io/node_modules/metalsmith-watch/dist/index.js:116
      if (filenames.indexOf(collections[key][i].filename) > -1) {
                                                ^

TypeError: Cannot read property 'filename' of undefined
    at /Users/Shared/Dropbox/Projects/jcrawford.github.io/node_modules/metalsmith-watch/dist/index.js:116:49
    at Array.forEach (<anonymous>)
    at removeFilesFromCollection (/Users/Shared/Dropbox/Projects/jcrawford.github.io/node_modules/metalsmith-watch/dist/index.js:113:28)
    at runAndUpdate (/Users/Shared/Dropbox/Projects/jcrawford.github.io/node_modules/metalsmith-watch/dist/index.js:139:5)
    at /Users/Shared/Dropbox/Projects/jcrawford.github.io/node_modules/metalsmith-watch/dist/index.js:215:5
    at Immediate.<anonymous> (/Users/Shared/Dropbox/Projects/jcrawford.github.io/node_modules/co/index.js:52:14)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
```

**Comment by jcrawford** [comment]
I think the issue is that collections[key][i] is not always the file in my articles collection.  As you can see from my screenshot I have `collections[articles][first-series][first-page.html].filename` so I think you need some recursive logic to check and see if `collections[key][0]` is another object of data and if so get the filename from there, otherwise check to see if that is another object of data, until you cannot go down any further.

<img width="372" alt="screen shot 2018-12-13 at 10 52 28 am" src="https://user-images.githubusercontent.com/875341/49950327-9bc21380-fec5-11e8-89a0-1d1a526bf3e0.png">

**Comment by jcrawford** [comment]
Added a pull request https://github.com/FWeinb/metalsmith-watch/pull/49
